### ISSUE TITLE
re-pin concurrent-ruby

### ISSUE THREAD

**Issue by gkuchta** [repeatedly/fluent-plugin-beats#10]
Is it possible to bump concurrent-ruby? As is the version pin conflicts with recent i18n pins (concurrent-ruby > 1.0), so it won't work in conjunction with other plugins.

**Comment by rakeshpatri** [comment]
yes please. getting gemconflict error.

**Comment by repeatedly** [comment]
I just released v0.1.4 with relaxing concurrent-ruby version.
Try it :)
