### ISSUE TITLE
Is this a dead project, or still being maintained?

### ISSUE THREAD

**Issue by jdevalk2** [repeatedly/fluent-plugin-beats#15]
See topic.
I see unanswered issues for a couple of months, considering evaluation of this plugin.

**Comment by repeatedly** [comment]
Yes, plugin itself is still maintained for critical problem.
The problem is I sometimes busy for fluentd core and others.
So I want new maintainer for this project.
Fortunately, lumberjack protocol is not changed so plugin itself is stable.

**Comment by jdevalk2** [comment]
Awesome thanks, you should document it on the main readme as well.
