### ISSUE TITLE
Support for multi-worker configuration

### ISSUE THREAD

**Issue by martinhynar** [repeatedly/fluent-plugin-beats#9]
Hi, I am using fluent-plugin-beats v0.1.3 and it is not possible to switch on multi-worker configuration. What I get is

`Plugin 'beats' does not support multi workers configuration (Fluent::BeatsInput)"`

**Comment by DaemonDude23** [comment]
The above PR was merged to enable multiple workers, and a new release generated.
This issue can be closed.
